### ISSUE TITLE
[UI] Users of Local Provider are unable to create new designs

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#11963] opened 2024-09-10 22:09 UTC
### Current Behavior

<img width="1584" alt="Screenshot 2024-09-10 at 5 07 49 PM" src="https://github.com/user-attachments/assets/b2154128-2f0b-4e21-a77d-febb299dd3ce">

### Environment

- Meshery Server Version: stable-v0.7.94

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by leecalcote** [comment] 2024-09-10 22:09
// @dragon-slayer875

**Comment by Yashsharma1911** [comment] 2024-09-12 21:32
Ohh ho! not good I'll fix it

**Comment by sudhanshutech** [comment] 2024-09-16 13:09
@Yashsharma1911 is this done?

**Comment by leecalcote** [comment] 2024-09-21 17:47
👀

**Comment by leecalcote** [comment] 2024-09-21 17:48
A high priority issue...

**Comment by Yashsharma1911** [comment] 2024-09-22 23:14
Although this issue is fixed in latest, however not the root cause, I just got to know after I fixed design not getting load in designs page it automatically fixed buttons issue and allow you to create design, however, I tested by blocking pattern API and got to know if there is no response from API, buttons doesn't load on UI, I'm fixing this dependency issue.

**Comment by Yashsharma1911** [comment] 2024-10-09 14:29
This issue is now fixed

**Closed by Yashsharma1911** 2024-10-09 14:29 UTC
Labels: kind/bug, language/javascript, component/ui, priority/high, framework/react
