### ISSUE TITLE
[UI] Clone Icon size too large

### ISSUE THREAD

**Issue by MUzairS15** [meshery/meshery#6411] opened 2022-10-19 15:23 UTC
#### Current Behavior

Clone icon size is too large to fit into the button completely.
<img width="253" alt="Screenshot 2022-10-19 at 8 48 51 PM" src="https://user-images.githubusercontent.com/79860504/196734782-7c851f3c-2a3e-4f0c-8be2-8a9fc2f97443.png">

#### Desired Behavior

Make icon size reasonable.
#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by neeraj-2** [comment] 2022-10-19 15:25
would like to fix it up first. Can I @MUzairS15

**Comment by tinniaru3005** [comment] 2022-10-19 16:26
Hey @MUzairS15, I would like to work on it. Could you please assign it to me?

**Comment by legendarykamal** [comment] 2022-10-19 17:07
@neeraj-2 since you are already working on the tooltip recently , lets let @tinniaru3005 proceed with this one. 

@tinniaru3005 go ahead 👍 .

**Comment by MUzairS15** [comment] 2022-10-19 17:07
@neeraj-2 Since you already have https://github.com/meshery/meshery/issues/6410 on your plate, let's @tinniaru3005 take on this.

**Comment by legendarykamal** [comment] 2022-10-19 17:07
oh @MUzairS15 😆

**Comment by tinniaru3005** [comment] 2022-10-21 22:19
Hey @MUzairS15 and @legendarykamal, Can you please point me to the page on the website where the icon is present?

**Comment by MUzairS15** [comment] 2022-10-22 01:46
In the left hand side you will find `Configuration` menu Select `Patterns` from there.

**Comment by tinniaru3005** [comment] 2022-10-22 01:53
> In the left hand side you will find `Configuration` menu Select `Patterns` from there.

In the `landing page` I couldn't find any configuration menu. So could you please link the page where the change is required?

**Comment by MUzairS15** [comment] 2022-10-22 02:05
<img width="1440" alt="Screenshot 2022-10-22 at 7 35 12 AM" src="https://user-images.githubusercontent.com/79860504/197313015-47b1fb7c-42f2-4a0b-b986-dced908f9923.png">

**Comment by tinniaru3005** [comment] 2022-10-23 08:37
Hey @MUzairS15, can you please tell me how can I reach this page from the [home page](https://meshery.io/)

**Comment by legendarykamal** [comment] 2022-10-23 08:55
@tinniaru3005 meshery and `meshery.io` are different. 
With this in place I doubt if you have meshery setup 🤔. If not then please unassign yourself and let someone else take it by then. Get the project setup running and then ask for assignments for the related issues. 

`meshery/meshery` is the one for running meshery ui. This repo is for this project only and `meshery.io` repo is different.

**Comment by tinniaru3005** [comment] 2022-10-23 09:17
> @tinniaru3005 meshery and `meshery.io` are different. With this in place I doubt if you have meshery setup thinking. If not then please unassign yourself and let someone else take it by then. Get the project setup running and then ask for assignments for the related issues.
> 
> `meshery/meshery` is the one for running meshery ui. This repo is for this project only and `meshery.io` repo is different.

Yes I did that. :)

**Comment by adithyaakrishna** [comment] 2022-10-23 09:29
@legendarykamal Wanna take this up? 👀

**Comment by legendarykamal** [comment] 2022-10-25 09:14
While my advice was solely in the favour of the assignee , some basic steps before taking on any issue as one might face challenges while setting up, the history proves.

Yes @adithyaakrishna I was waiting for someone to show up in the meantime , but no1 did till now , so I would be happilly proceeding with this 😅 .

**Comment by adithyaakrishna** [comment] 2022-10-25 11:41
Awesome Awesome  @legendarykamal 🎉

**Comment by AbhishekTiwari23** [comment] 2022-10-25 15:48
@legendarykamal, sir, if you don't mind, can I give it a try as my first issue for meshery?
Thanks.

**Comment by legendarykamal** [comment] 2022-10-25 17:12
@AbhishekTiwari23 I wish you were a little earlier I would have passed it to you,but the issue is no more (is Fixed ) .
Nevertheless, there are others to try your hands in. I will help you find one if you don't get :) 

here's the glimpse
![image](https://user-images.githubusercontent.com/95926324/197838720-c82f87bd-6575-48e2-8abe-70cb21d150c1.png)

**Comment by AbhishekTiwari23** [comment] 2022-10-25 17:37
> @AbhishekTiwari23 I wish you were a little earlier I would have passed it to you,but the issue is no more (is Fixed ) . Nevertheless, there are others to try your hands in. I will help you find one if you don't get :)
> 
> here's the glimpse ![image](https://user-images.githubusercontent.com/95926324/197838720-c82f87bd-6575-48e2-8abe-70cb21d150c1.png)

Thanks, sir. I will look for others. I need a little help. I am looking for documentation on how I can install service mesh and run an adapter.

**Comment by AbhishekTiwari23** [comment] 2022-10-25 17:38
And if there is any video or tutorial, then it will be best. Please help if there is any such resource.

**Closed** 2022-10-26 03:32 UTC
Labels: kind/bug, hacktoberfest, language/javascript, component/ui, framework/react
