### ISSUE TITLE
[ UI ] ViewSwitch acts weird 

### ISSUE THREAD

**Issue by harkiratsm** [meshery/meshery#5886] opened 2022-07-27 05:08 UTC
#### Current Behavior

Currently  we have a ```ViewSwitch``` to switch ```grid``` & ```table``` view for ```application/filter/design``` .
Suppose if I am on ```table``` view ,If I again press the table view button we get ```blank``` section. 

![ll](https://user-images.githubusercontent.com/71957674/181165239-4a002c8e-7cc4-4a83-b3c5-d253d27904be.png)

#### Expected Behavior

We should correctly handle the state of  ```ViewSwitch```.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment] 2022-07-27 09:36
hi @harkiratsm  i also saw this :eyes:  
what should be the expected behaviour like should we disable it for clicking  more number of times continuosly the same bar?

**Comment by Chadha93** [comment] 2022-07-27 09:38
@harkiratsm Since you are working on a similar behavior of the issue wrt an empty state. Will you also cover the fix for this in the same PR? https://github.com/meshery/meshery/pull/5853

**Closed** 2022-07-28 06:45 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react
