### ISSUE TITLE
[Docs] Improve code formatting

### ISSUE THREAD

**Issue by vishalvivekm** [meshery/meshery#9897] opened 2024-01-09 13:38 UTC
### Current State
On https://docs.meshery.io/installation/docker/docker-extension page, the current state of code snippets: 
![Screenshot from 2024-01-09 18-59-30](https://github.com/meshery/meshery/assets/110674407/bd5ccade-6023-428e-a5b4-cd6942a661ac)

### Desired State
format it to look like:
![Screenshot from 2024-01-09 19-04-34](https://github.com/meshery/meshery/assets/110674407/54da3c6c-c93b-4805-90ae-5577beb5af04)

Note: Don't modify the actual content.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by rishidyno** [comment] 2024-01-23 22:06
Hi @vishalvivekm Could you please assign me this issue?

**Comment by sandramsc** [comment] 2024-01-24 11:10
Hi @rishidyno great that you're eager to contribute, however in future please be sure to check previous conversation history on an issue including checking the assignee box at the top right corner to be sure the issue isn't already assigned to contributor (in this case it is).

**Closed** 2024-02-21 00:44 UTC
Labels: good first issue, area/docs, language/markdown, framework/jekyll
