### ISSUE TITLE
[UI] Registry: Same model count is reported for each Registrant

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#12275] opened 2024-10-04 19:23 UTC
### Current Behavior
All registrants have the same model count.

### Expected Behavior
The model counts in parentheses should not be the same between registrants.
`https://playground.meshery.io/api/meshmodels/registrants`
This endpoint is intended to display the count.
### Screenshots/Logs

<img width="559" alt="Screenshot 2024-10-04 at 2 21 03 PM" src="https://github.com/user-attachments/assets/2a383fe4-c45e-4412-aceb-bd9975acc4ed">

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by prachinandi** [comment] 2024-10-04 19:56
I want to work on this, @leecalcote can you please assign me

**Comment by prachinandi** [comment] 2024-10-05 22:37
> @prachinandi, sounds great. Thanks much for jumping in and volunteering. In an effort to help guarantee your success in undertaking assignment of the issue, will you:
> 
> 1. confirm that you're able to build the project, specifically, the components necessary to resolve this issue.
> 2. confirm the approach you intend to take to resolve the issue.

Yes @leecalcote I have almost set up the project locally, have some issues in build trying to resolve it actually. 

And regarding the approach I think it might be a simple fix. If the API is returning correct model count the issue might be in the frontend in displaying this data. (Chances that the data mapped from API to frontend is incorrect not sure).                                                     

If the issue is with API then need to check the backend logic, that if you can confirm that what response are we getting?

**Comment by prachinandi** [comment] 2024-10-05 22:59
I got this issue "unable to download meshery.tar.gz file from https://github.com/meshery/meshery/releases/download/v0.7.114/mesheryctl_0.7.114_Darwin_arm64.tar.gz. Set MESHERY_VERSION environment variable to a different version and re-run. For example: export MESHERY_VERSION=v0.1.6" when I try to deploy in docker

**Comment by Aryan4884** [comment] 2024-10-11 13:42
@leecalcote if no one working, i would like to take this one.
![Screenshot 2024-10-11 182601](https://github.com/user-attachments/assets/97921541-ef50-4fa2-b201-a0481ff1a538)
I think it will have to display the model count according to model count mentioned in summary for that individual registrant(e.g-534 for Artifact Hub) in advance details section which is the fetched data.But it is mentioning the global count of model which is common for all the registrants making them all same.
Let me know if I am wrong anywhere.

**Comment by leecalcote** [comment] 2024-10-11 13:46
@Aryan4884 how's your Golang and your React? Are you comfortable with both or one more than the next or neither?

**Comment by leecalcote** [comment] 2024-10-11 13:47
@prachinandi, my apologies, I completely missed your prior messages. Do post on https://discuss.meshery.io, if you're still experiencing challenges getting setup.

**Comment by Aryan4884** [comment] 2024-10-11 20:17
@leecalcote I have an experience of 1.5 years in React and a beginner in Golang.

**Comment by leecalcote** [comment] 2024-10-11 20:47
@Aryan4884, ok, very good. Depending upon what you find, it might be the API (golang) that needs ultimately enhanced or it might just be the client's handling of the responses. Aggregation and computation should be (must be) handled server-side. Let me (and the other contributors) know what you find. 👍

**Comment by sudhanshutech** [comment] 2024-10-17 13:37
@Aryan4884 whats the progress? Its an urgent item.

**Comment by leecalcote** [comment] 2024-10-17 13:46
@Yashsharma1911, help, help. 🙏

**Comment by Aryan4884** [comment] 2024-10-17 18:17
@leecalcote Sorry for inconvenience caused ,wasn't aware that this issue is an urgent one. I am new to the codebase and having little hard time in getting it in (making changes without conflict errors ).I will let u know as soon as I make any progress.In the mean time, since its an urgent one ,u may unassign me and assign others who can solve this quickly.

**Comment by kingdarabahmad** [comment] 2024-10-17 18:59
@leecalcote if you allow me i can resolve this issue

**Comment by kingdarabahmad** [comment] 2024-10-17 19:47
@leecalcote  i tried to resolve this  issue the problem is that each registrants type has some models count but this models count contains the data of all types of registrants. so i have filtered the models  based on the kind(artifacthub,meshery and etc...)  of the registrants. so it is showing correct result. 

screenshot 
<img width="1065" alt="Screenshot 2024-10-18 at 1 07 27 AM" src="https://github.com/user-attachments/assets/08409623-b128-4bf0-bd83-93daa1efc176">

**Comment by kingdarabahmad** [comment] 2024-10-19 08:15
@leecalcote @sudhanshutech should i 
proceed with the solution or not??

**Comment by eyeaadil** [comment] 2024-10-30 19:04
@leecalcote @sudhanshutech please assign this to me.

**Comment by Yashsharma1911** [comment] 2024-10-31 21:12
> @leecalcote i tried to resolve this issue the problem is that each registrants type has some models count but this models count contains the data of all types of registrants. so i have filtered the models based on the kind(artifacthub,meshery and etc...) of the registrants. so it is showing correct result.
> 
> screenshot <img alt="Screenshot 2024-10-18 at 1 07 27 AM" width="1065" src="https://private-user-images.githubusercontent.com/64286022/377612534-08409623-b128-4bf0-bd83-93daa1efc176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MDkzMjIsIm5iZiI6MTczMDQwOTAyMiwicGF0aCI6Ii82NDI4NjAyMi8zNzc2MTI1MzQtMDg0MDk2MjMtYjEyOC00YmYwLWJkODMtOTNkYWExZWZjMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDIxMTAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjBhNzVhYTU4MWEyZDlhOWNlYzEwMjJlZDdmMGZiMmFjNTBiNjI0ZDYzZTdlNTQwMWRiN2M5NzBlODQ1MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LL8dsYRH28UbkwFM3bt9nRZ85ryfRgx6nUNRDWHzrF0">

Thanks, everyone for raising your hand on this issue, @kingdarabahmad incase you have changes already please feel free to raise a quick PR for review and if possible by today.

Considering the urgency, I'll start working on this issue by this morning or afternoon in case we don't get a response.

**Closed** 2024-11-05 21:00 UTC
Labels: kind/bug, language/javascript, component/ui, issue/willfix, framework/react
