### ISSUE TITLE
[UI] Linkerd mesh not showing in the installed service mesh dashboard

### ISSUE THREAD

**Issue by alphaX86** [meshery/meshery#5357] opened 2022-04-07 14:40 UTC
#### Current Behavior

After I installed Linkerd for tests, Meshery installed necessary components to run Linkerd on system, but after installation, Linkerd didn't appear in the list even though all linkerd pods are active

#### Desired Behavior

Meshery should be able to detect Linkerd and show it in the installed service mesh dashboard

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/59508546/162226787-889c314d-8091-4ab4-854f-751890a3c73f.png)

![image](https://user-images.githubusercontent.com/59508546/162226888-0299c897-31a4-408d-bb39-fd12a2d33469.png)

![image](https://user-images.githubusercontent.com/59508546/162228870-e9e34842-ecbf-4a3f-ba0e-ef1e3695afc9.png)

#### Environment

- Browser: Chrome (via Brave)
- Host OS: Linux (Ubuntu-20.04 via WSL2)
- Meshery Server Version: stable-v0.6.0-rc-5j
- Meshery Client Version: stable-v0.6.0-rc-5b
- Platform: Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment] 2022-04-10 13:28
@Akshit42-hue @Harshit-Dandriyal, would one of you like to investigate?

**Comment by Harshit-Dandriyal** [comment] 2022-04-10 16:56
@leecalcote Sure, my pleasure :)

**Comment by Akshit42-hue** [comment] 2022-04-10 17:02
I am investigate on it but can't find any leads

**Comment by leecalcote** [comment] 2022-04-12 21:57
Thank you, gents. Examine what string matching is taking place here and what match there must be in order for Linkerd to show up.

**Comment by jbyers19** [comment] 2022-07-06 15:10
This is still an issue. #5395 is a duplicate of this one, but contains more details about the root problem so closing this one instead.

**Closed by jbyers19** 2022-07-06 15:10 UTC
Labels: kind/bug, help wanted, language/javascript, component/ui, framework/react
