### ISSUE TITLE
logo center issue

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7996] opened 2023-06-29 13:43 UTC
### Description
we should centered these logos respective to their text at https://docs.meshery.io/
### Expected Behavior
logo should be centered

### Screenshots

<img width="234" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/983e5ac6-5d18-421f-8b02-ae196eba2ecd">
<img width="136" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/3f27c758-421d-4790-88ac-5987edbf510f">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment] 2023-06-30 20:35
Duplicate of #7979

**Closed** 2023-06-30 20:36 UTC
Labels: kind/bug
