### ISSUE TITLE
[mesheryctl] `system restart` fails

### ISSUE THREAD

**Issue by piyushsingariya** [meshery/meshery#4796] opened 2021-12-20 06:13 UTC
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior

```
❯ mesheryctl system restart
Restarting Meshery...
Meshery deployments will be deleted from your cluster. Are you sure you want to continue [y/n]? y 
Stopping Meshery...
Deleting Meshery Namespace...
Meshery is stopped.
Starting Meshery...
⡿ Deploying Meshery on Kubernetes Error: cannot start Meshery: create: failed to create: secrets "sh.helm.release.v1.meshery.v1" is forbidden: unable to create new content in namespace meshery because it is being terminated
Usage:
  mesheryctl system restart [flags]

Flags:
  -h, --help          help for restart
      --skip-update   (optional) skip checking for new Meshery's container images.

Global Flags:
      --config string    path to config file (default "/home/nectar/.meshery/config.yaml")
  -c, --context string   (optional) temporarily change the current context.
  -v, --verbose          verbose output
  -y, --yes              (optional) assume yes for user interactive prompts.

```

#### Environment

- Host OS:  Linux 
- Meshery Server Version: stable-latest
- Meshery Client Version: stable-latest
- Platform:  Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by piyushsingariya** [comment] 2021-12-20 06:14
CC @panyuenlau @navendu-pottekkat @leecalcote @Revolyssup @warunicorn19

**Comment by piyushsingariya** [comment] 2021-12-20 06:16
@hexxdump

**Comment by navendu-pottekkat** [comment] 2021-12-21 12:08
Duplicate of https://github.com/meshery/meshery/issues/4665

**Closed by navendu-pottekkat** 2021-12-21 12:08 UTC
Labels: kind/bug, issue/duplicate, component/mesheryctl, language/go
