### ISSUE TITLE
[UI] Empty space in the list of users

### ISSUE THREAD

**Issue by MitAbhay** [meshery/meshery#7705] opened 2023-05-19 09:25 UTC
#### Current Behavior

![image](https://github.com/meshery/meshery/assets/76659113/16d90224-83f3-4206-8992-76b94d898a94)

As we can see the image space in the 2nd row and 1st column is empty. By Inspecting I found that it is the place for the Layer5 logo. Due to an incorrect aspect ratio, we are unable to see the logo.

#### Desired Behavior

The size of the layer5 logo must be corrected to show the image correctly in the empty space.
![image](https://github.com/meshery/meshery/assets/76659113/38a400b0-7f74-4da2-bf18-474a84774ab5)

#### Environment

- Browser: Firefox
- Host OS: Linux 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by 8rxn** [comment] 2023-05-19 11:49
@MitAbhay What page does this issue exist in? It seems the issue belongs to meshery.io repository.

@Shivam-AfA, you might want to take a look at this.

**Comment by MitAbhay** [comment] 2023-05-19 13:28
Yes, the issue is in hero page :  https://meshery.io/

**Comment by sanudutta45** [comment] 2023-05-20 12:26
I couldn't reproduce it. The layer 5 logo is already there in the empty space.
![image](https://github.com/meshery/meshery/assets/60579654/958c4813-cffb-47f4-b787-0ce27ec8fac1)

**Comment by MitAbhay** [comment] 2023-05-20 16:10
I think the problem is in Firefox then

**Comment by sebzz2k2** [comment] 2023-05-27 15:18
@sanudutta45 
I could reproduce this issue on firefox and i am using linux as stated by @MitAbhay

**Comment by thisiskaransgit** [comment] 2023-06-17 14:42
@MitAbhay, the issue had to be raised in [Meshery.io](github.com/meshery/meshery.io), the issue has been fixed already, thus closing it. Thanks for looking though.

**Closed by thisiskaransgit** 2023-06-17 14:42 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react
