### ISSUE TITLE
[mesheryctl] Migration from kubectl to go-client

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2425] opened 2021-02-21 13:40 UTC
> Will the usage of MeshKit and k8s go-client be on a future PR?
> 
> Suggestion for failing lint checks is to use [golangci-lint](https://github.com/golangci/golangci-lint) and install it locally and run it. It will show the lines where the lint check fails.

Will take care of the go-client implementation in new PR.

_Originally posted by @hexxdump in https://github.com/layer5io/meshery/issues/2419#issuecomment-781061433_

**Comment by piyushsingariya** [comment] 2021-03-25 06:41
@leecalcote I think this should be closed!

**Comment by hexxdump** [comment] 2021-03-25 08:41
@piyushsingariya 
This is not complete yet. https://github.com/meshery/meshery/pull/2513 fixes only a part of the issue.

Here is the comment by @leecalcote 

=======
Our two objectives:

Eliminate external dependencies where feasible.
1. Enable the same configuration generation ability in mesheryctl and Meshery through MeshKit
2. Current state (inclusive of this PR):

Dependencies that remain:
1. kubectl for GKE
2. az for AKS
3. aws for EKS

Dependencies eliminated:
1. MeshKit for Minikube (k8s go client)
Issues to be created in support of each of these four Kubernetes platforms in MeshKit
=====

@leecalcote, Should we have 3 separate problem reports or use this PR itself?

**Comment by pottekkat** [comment] 2021-03-26 17:17
@hexxdump As we start working on this, it might be best if we create a new issue and assign child issues if it is possible. This would be similar to the [[mesheryctl] [epic] provide support for platform: kubernetes](https://github.com/meshery/meshery/issues/2307) where each of the remaining dependencies would be a subset of `platform: kubernetes`

**Comment by hexxdump** [comment] 2021-05-06 06:14
Will use this issue to fix the `mesheryctl system config gke` command.

Opened child PRs to handle AKS and EKS configs:
#2843 Migrate 'system config aks' to golang SDK
#2842 Migrate 'system config eks' to golang SDK

**Comment by hexxdump** [comment] 2021-06-15 10:13
working on it.

**Comment by alphaX86** [comment] 2021-07-26 02:35
Guys..... May I know exactly what this needs to be done? 😅 And isn't the migration already over? Coz I saw some files used `meshkit` instead of `kubectl`

**Comment by leecalcote** [comment] 2021-07-26 02:59
@alphaX86 will you perform a search of the mesheryctl codebase and confirm that you don't see any references to `kubectl`? Will you confirm that `kubectl` is not included in mesheryctl's preflight checks?

**Comment by alphaX86** [comment] 2021-07-26 03:07
Hmm alright, I'll perform a clean sweep and check if any file uses `kubectl` if not, then the issue can be closed. Else, the issue is WIP. 👍

**Comment by alphaX86** [comment] 2021-07-26 13:30
@leecalcote so far I got these info

- `check.go` uses `utils` modules to obtain `kubectl` version and a function (see last line)
- `logs.go` uses `for` loop instead of `kubectl get pods -n meshery` (No direct reference)
- `restart.go` uses the same method as previous one for obtaining info on pods
- `start.go` uses `utils` module (no direct reference found)
- `status.go` uses `for` loop method

But the program `healthcheck.go` uses `exec` function which the `kubectl` is made to run (Lines 70 to 90)
![image](https://user-images.githubusercontent.com/59508546/126996850-2b482228-303d-42ef-87f1-f6b70c845d73.png)

`script.go` uses `kubectl` too but IG it's needed to generate manifests I hope.
![image](https://user-images.githubusercontent.com/59508546/126996886-d606aefe-333a-4735-a3d0-84176bfe307e.png)

**Comment by alphaX86** [comment] 2021-07-26 13:34
This is what I got in short :)

**Comment by piyushsingariya** [comment] 2021-07-26 14:38
In `check.go` we don't have any other way to obtain kubectl's version so that could be count as an exception.

**Comment by alphaX86** [comment] 2021-07-26 14:40
> In `check.go` we don't have any other way to obtain kubectl's version so that could be count as an exception.

I agree bro, that's what I said these are the ones I got. Even `kubectl` is needed in `scripts.go` I hope after seeing all the codebase

**Comment by alphaX86** [comment] 2021-07-26 14:40
So guys, what's your say? Can we close this issue then?

**Comment by hexxdump** [comment] 2021-07-27 16:08
@alphaX86 , the intent of this PR is to move away from the kubectl commands in script.go and to start using the client go APIs. I have not made much progress with this, would like to keep this issue for tracking.

**Comment by alphaX86** [comment] 2021-07-27 16:10
@hexxdump alright. Issue stays open then. Good luck 👍

**Comment by leecalcote** [comment] 2021-09-22 19:05
As we near v0.6.0 release, how are we feeling about the status of this effort?

**Closed** 2023-08-17 22:27 UTC
Labels: component/mesheryctl, issue/willfix
