### ISSUE TITLE
The MeshMap hovering effect needs improvement.

### ISSUE THREAD

**Issue by Modern-artist** [meshery/meshery#9142] opened 2023-10-18 11:29 UTC
### Current Behavior
Currently, when we hover **MeshMap Icon**, the MeshMap icon moves, and when we expand the navigator, the hover icon still moves(it should not when expanded).

### Expected Behavior
It should behave like other icons.

### Screenshots/Logs
https://github.com/meshery/meshery/assets/90668597/7f005b1a-be2f-49b8-bc47-0dac4483e9cb

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Kamalesh-Seervi** [comment] 2023-10-18 16:42
can I work on this bug

**Comment by Modern-artist** [comment] 2023-10-19 02:46
Go ahead @Kamalesh-Seervi

**Comment by Kamalesh-Seervi** [comment] 2023-10-19 18:14
Yeh sure

**Comment by Shreyas0410** [comment] 2023-10-22 07:36
If the issue is still open I would like to work on this.

**Comment by hemantmm** [comment] 2023-11-03 17:55
@Modern-artist I would like to work on this issue.

**Comment by Modern-artist** [comment] 2023-11-05 05:14
@Kamalesh-Seervi whats your statue on this issue?

**Comment by Yashsharma1911** [comment] 2023-11-15 10:29
@Kamalesh-Seervi as there is no response, I'm reassigning this issue

**Comment by nick2432** [comment] 2023-11-15 10:32
can i work on this?

**Comment by vaibhavpnimkar** [comment] 2023-11-15 12:55
hey @Yashsharma1911 can i work on this? seems like i can fix this!!

**Comment by nick2432** [comment] 2023-11-15 15:14
> @nick2432 sure, can you confirm that you are successfully able to run Meshery in your local environment?
I am encountering this error
![Screenshot from 2023-11-15 20-41-10](https://github.com/meshery/meshery/assets/77477551/4bb9d701-b010-4567-a765-1f5d1a9b7b1e)

**Comment by nick2432** [comment] 2023-11-15 15:30
> @nick2432 sure, can you confirm that you are successfully able to run Meshery in your local environment?
I am encountering this error
![image](https://github.com/meshery/meshery/assets/77477551/19fea61a-10cc-4acc-a1d4-373ff96baf54)

**Comment by Yashsharma1911** [comment] 2023-11-15 18:47
Thankyou @vaibhavpnimkar for raising your hand, as @nick2432 asked first I think let's help him here to get this issue fixed, @vaibhavpnimkar you can help here by reviewing PR and making sure it fixes the issue ^^

**Comment by Yashsharma1911** [comment] 2023-11-15 18:48
> > @nick2432 sure, can you confirm that you are successfully able to run Meshery in your local environment?
> > I am encountering this error
> > ![image](https://user-images.githubusercontent.com/77477551/283165086-19fea61a-10cc-4acc-a1d4-373ff96baf54.png)

Have you run `make ui-setup` first?

**Comment by nick2432** [comment] 2023-11-15 18:54
> > > @nick2432 sure, can you confirm that you are successfully able to run Meshery in your local environment?
> > > I am encountering this error
> > > ![image](https://user-images.githubusercontent.com/77477551/283165086-19fea61a-10cc-4acc-a1d4-373ff96baf54.png)
> 
> Have you run `make ui-setup` first?

yes

**Comment by nick2432** [comment] 2023-11-15 19:41
@Yashsharma1911  it is working now
![Screenshot from 2023-11-16 01-07-15](https://github.com/meshery/meshery/assets/77477551/76475d8b-d491-43df-9f09-9ef65cd7fd70)

**Comment by nick2432** [comment] 2023-11-16 03:01
@Yashsharma1911  Could you please assign me now

**Comment by Yashsharma1911** [comment] 2023-11-18 22:44
Ohh good, yes please go ahead and raise PR

**Comment by adityaverma6384** [comment] 2023-11-24 21:18
is it working

**Comment by nick2432** [comment] 2023-11-28 10:07
![main](https://github.com/meshery/meshery/assets/77477551/a799ffaf-834d-4db4-a509-46bd8d5dc60f)
I am unable to locate the meshmap icon

**Comment by vaibhavpnimkar** [comment] 2023-11-28 14:28
@nick2432 try fetching changes from master branch

**Comment by nick2432** [comment] 2023-11-28 16:58
> @nick2432 try fetching changes from master branch

still i am unable to locate 
Should I sign up first?![Screenshot from 2023-11-28 22-27-16](https://github.com/meshery/meshery/assets/77477551/363e1a1e-2308-4a55-9c4f-9190c312035d)

**Comment by vaibhavpnimkar** [comment] 2023-11-28 17:04
you should have early acess you will get a mail after sign up from that you can acess meshmap

**Comment by nick2432** [comment] 2023-11-30 06:07
@vaibhavpnimkar 
it is enabled on playground.meshery.io but not on my localhost
![Screenshot from 2023-11-30 11-37-06](https://github.com/meshery/meshery/assets/77477551/30bf9c1d-fb9a-4013-90aa-a5e3d0825c0b)

**Comment by vaibhavpnimkar** [comment] 2023-11-30 06:09
login with same account on localhost

**Comment by Yashsharma1911** [comment] 2023-11-30 06:44
> login with same account on localhost

+1

**Comment by nick2432** [comment] 2023-11-30 10:45
@Yashsharma1911  @vaibhavpnimkar Bro, I am only seeing two options: 'None' and 'Meshery.' In 'None,' the localhost:3000 opens directly without providing any login option, and in 'Meshery Playground,' it opens a different location, not localhost.
![Screenshot from 2023-11-30 16-11-43](https://github.com/meshery/meshery/assets/77477551/bd5adb7f-4182-452f-8789-48a0132d7905)

**Comment by sandramsc** [comment] 2024-01-04 11:12
This issue has been open for some time with no recent activity, unassigning to open it up for new contributors to give it a go.

**Comment by Yashsharma1911** [comment] 2024-01-04 18:56
Thankyou @sandramsc we don't have this issue anymore, closing it as completed

**Closed by Yashsharma1911** 2024-01-04 18:56 UTC
Labels: kind/bug, good first issue, component/ui
