### ISSUE TITLE
[CI] "ModuleNotFoundError" UI Integration tests failing

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#4993] opened 2022-01-26 19:50 UTC
#### Current Behavior
See - https://github.com/meshery/meshery/runs/4956701283?check_suite_focus=true

Screenshot:
<img width="1039" alt="CleanShot 2022-03-23 at 08 40 28@2x" src="https://user-images.githubusercontent.com/23443575/159725301-8f623752-0dec-4126-8f9a-f014b55d6540.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment] 2022-01-26 19:50
@MarioArriaga92, I wonder if you might investigate...

**Comment by MarioArriaga92** [comment] 2022-01-26 20:42
Taking a look at why this below module import from `./pages/_document.js` generated by ui/.babelrc can't be resolved:
`import flush from "styled-jsx/server";`

**Comment by MarioArriaga92** [comment] 2022-01-26 20:51
I don't think npm package.json's 'dependencies' versions accept the 'latest' value:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies

**Comment by MarioArriaga92** [comment] 2022-01-26 20:52
Curious command to start meshery ui locally barely started complaining about this

**Comment by MarioArriaga92** [comment] 2022-01-26 21:01
@leecalcote @warunicorn19 can I suggest a rebase from master onto addendum_governance branch? Probably it was branched at a moment where there was something off with ui package.json

**Comment by MarioArriaga92** [comment] 2022-01-26 21:05
Actually, if only change is in markup why are those tests running in the first place?

**Comment by MarioArriaga92** [comment] 2022-01-26 21:17
Regarding the failure itself, looks like we should configure babel presets for styled-jsx in [/ui/.babelrc](https://github.com/meshery/meshery/blob/master/ui/.babelrc):
https://nextjs.org/docs/advanced-features/customizing-babel-config

**Comment by MarioArriaga92** [comment] 2022-01-26 21:18
This steps might help @leecalcote:
https://github.com/vercel/styled-jsx#getting-started

**Comment by MarioArriaga92** [comment] 2022-01-26 21:19
Specifically this part:
```
Next, add styled-jsx/babel to plugins in your babel configuration:

{
  "plugins": ["styled-jsx/babel"]
}
```

**Comment by MarioArriaga92** [comment] 2022-01-26 21:21
but not sure, as per [this other section](https://github.com/vercel/styled-jsx#using-in-nextjs), it shouldn't be needed:
`Next.js automatically configures styled-jsx with babel or swc, you don't have to configure it manually.`

**Comment by MarioArriaga92** [comment] 2022-01-26 21:22
So I'd look into any webpack specific configurations missing

**Comment by MarioArriaga92** [comment] 2022-01-26 21:23
Found it!
https://github.com/vercel/styled-jsx#nextjs

**Comment by MarioArriaga92** [comment] 2022-01-26 21:24
We need this kind of configuration in our [/ui/next.config.js](https://github.com/meshery/meshery/blob/master/ui/next.config.js) file
![Screen Shot 2022-01-26 at 15 23 27](https://user-images.githubusercontent.com/23443575/151249255-edac7a93-b040-4521-a9fc-f63aefa3b164.png)

**Comment by MarioArriaga92** [comment] 2022-02-16 20:11
Taking a look

**Comment by MarioArriaga92** [comment] 2022-03-23 14:26
Is this issue still reproducing? exact issue is `Error: Cannot find module '/home/runner/work/meshery/meshery/ui/.next/server/pages-manifest.json'`

**Comment by MarioArriaga92** [comment] 2022-03-23 14:44
Haven't seen this error (which we noticed on "26 Jan in 6m 5s") in latest 50 build runs for our ci.yaml workflow so closing this issue
<img width="1039" alt="CleanShot 2022-03-23 at 08 40 28@2x" src="https://user-images.githubusercontent.com/23443575/159725301-8f623752-0dec-4126-8f9a-f014b55d6540.png">

**Closed by MarioArriaga92** 2022-03-23 14:44 UTC
Labels: area/ci
