### ISSUE TITLE
[Docs] The link in docs leads to an Error 404 page

### ISSUE THREAD

**Issue by pratik2315** [meshery/meshery#7125] opened 2023-02-20 20:10 UTC
#### Current State

When we paste the following link in the browser:
![image](https://user-images.githubusercontent.com/77961530/220190357-0ad18e95-e410-4753-9c80-d4c9b9b61922.png)

The result is this page:
![image](https://user-images.githubusercontent.com/77961530/220190480-0f7cb59a-1385-4973-8d96-d4f10a79a42f.png)

#### Desired State

This is due to one incorrectly typed extra slash. The correct link after the upcoming fix will lead to:

![image](https://user-images.githubusercontent.com/77961530/220190742-71e5cace-78d7-44a4-8292-b0e00df6016f.png)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by pratik2315** [comment] 2023-02-20 20:10
Hey there everyone! I would like to work on this issue if approved, please. Thanks😀

**Comment by Swathi-L** [comment] 2023-02-20 20:18
Hi @pratik2315, for minor bugs like this, you're welcome to submit a PR, the team will review and merge it.

**Comment by pratik2315** [comment] 2023-02-20 20:20
> Hi @pratik2315, for minor bugs like this, you're welcome to submit a PR, the team will review and merge it.

Hey there! Thanks. Are you saying in future I should refrain from creating an issue and directly create a PR or 

are you saying I should just create a PR without taking any maintainer's permission for minor issues like these?

Sorry if my question didn't make any sense😅

**Comment by Swathi-L** [comment] 2023-02-20 20:25
I meant you can create an issue and also submit a PR if you're confident about it. You need not wait till the issue is assigned to you to submit a PR is what I meant :-)

**Comment by pratik2315** [comment] 2023-02-20 20:34
> I meant you can create an issue and also submit a PR if you're confident about it. You need not wait till the issue is assigned to you to submit a PR is what I meant :-)

Makes sense! Thanks a lot😁

**Closed** 2023-02-20 21:15 UTC
Labels: area/docs, language/markdown, framework/jekyll
