### ISSUE TITLE
[UI] Updated SVG system and compatibility with dark mode

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#7614] opened 2023-04-26 12:18 UTC
#### Current Behavior
At present, we are using SVG scaling as defined here - https://github.com/meshery/meshery/blob/master/ui/css/icons.styles.js. 
There are more icons that need to be updated with this system.

#### Desired Behavior
For custom icons (SVGs):

1. Each icon should have a `primaryFill` and `secondaryFill` property to make it darkMode friendly.
    -  example - `<DesignsIcon
                      primaryFill={theme.palette.lightDarkJungleGreen}
                      secondaryFill={theme.palette.superLightDarkJungleGreen}
                    />`

2. Each SVG should have a default color that can be overridden according to need.
    - example - `function SvgIcon({ color = "green", ...props }) {
 							 return (
   						 <svg viewBox="0 0 24 24" fill={color} stroke={color} {...props}>
    	  <path d="M0 0h24v24H0z" fill="none" />
     		 <path d="M12 2L2 7v10l10 5 10-5V7L12 2z" />
  		  </svg>
 				 )
				}`
       Usage - `<SvgIcon color="blue" />`

3. All the icons should be updated with the existing SVG system.

#### Acceptance Tests
SVGs should be working fine on all browser types. 

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MdSahil-oss** [comment] 2023-04-26 12:48
@leecalcote I'd like to work on it. please assign it to me.

**Comment by duckling69** [comment] 2023-05-10 10:08
Hey @vishalvivekm can i work on this issue ? if issue is in stale state

**Comment by vishalvivekm** [comment] 2023-05-10 10:11
> Hey @vishalvivekm can i work on this issue ? if issue is in stale state 

First, Let's ask @MdSahil-oss about his progress on the issue.
@MdSahil-oss any update?

**Comment by MdSahil-oss** [comment] 2023-05-10 14:55
@duckling69 Yes, you can work on it, I haven't made any progress yes because of other on going stuffs.

**Comment by vishalvivekm** [comment] 2023-05-10 15:08
> @duckling69 Yes, you can work on it, I haven't made any progress yes because of other on going stuffs.

In which case, @duckling69 you've the green-light 🚀

**Comment by duckling69** [comment] 2023-05-10 17:53
@vishalvivekm I'd need a little guidance here

-  first the issue : can you confirm if the issue is asking me to update system by implementing following function or I just need to update the SVGs according to what issue says and that existing system already have these functions
- and if i need to update all SVGs according to this system am i supposed to give it secondary color according to what i think is the best or do I need to follow some rules

**Comment by vishalvivekm** [comment] 2023-05-10 18:56
> @vishalvivekm I'd need a little guidance here
> 
> * first the issue : can you confirm if the issue is asking me to update system by implementing following function or I just need to update the SVGs according to what issue says and that existing system already have these functions
> * and if i need to update all SVGs according to this system am i supposed to give it secondary color according to what i think is the best or do I need to follow some rules

Please refer to the discussion on the issue in the Dev Call of May 26th: [link](https://youtu.be/iZ4EWw-UYhI?t=2752) 
If you still have any doubts, feel free to post them here in [discuss forum](https://discuss.layer5.io) @duckling69

**Comment by leecalcote** [comment] 2023-07-04 11:51
@duckling69 how's this coming along?

**Comment by ranjanmangla1** [comment] 2023-07-10 17:32
if nobody is currently working on it, can you assign me this issue?

**Comment by duckling69** [comment] 2023-07-10 17:59
> if nobody is currently working on it, can you assign me this issue?

Sure you can go ahead with this 🚀

**Comment by thisiskaransgit** [comment] 2023-07-27 14:45
@ranjanmangla1, progress check...

**Comment by ranjanmangla1** [comment] 2023-07-27 17:43
@thisiskaransgit, almost every png has ben converted to svg, 2-3 files of meshery logo are remaining, resta re complete.
I think i may not be able to convert this imagae to svg: 
![image](https://github.com/meshery/meshery/assets/93506927/25133eab-b183-4d30-a563-ba17227c360d)

**Closed** 2023-09-30 15:06 UTC
Labels: kind/enhancement, language/javascript, component/ui, issue/willfix, framework/react, issue/remind
