### ISSUE TITLE
[UI]Search functionality not working 

### ISSUE THREAD

**Issue by sudhanshutech** [meshery/meshery#7617] opened 2023-04-27 06:02 UTC
#### Current Behavior

Currently the search property in `smi result` page and `design` page is not working and throwing same error numerous time

https://user-images.githubusercontent.com/90546692/234661855-d1057e98-f63e-4c7f-a6fe-953beb65fb5f.mp4

https://user-images.githubusercontent.com/90546692/234773031-bdc19a9b-b4b6-4ca2-bd9e-65ce5e64043f.mp4

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by MdSahil-oss** [comment] 2023-04-28 19:00
@sudhanshutech Can you please update your code locally with master branch and confirm me that you're able to see search Icon or not because I'm not able to see it :(

**Comment by duckling69** [comment] 2023-05-06 13:31
Hey @sudhanshutech i'd like to work on this issue can you assign it to me

**Comment by vishalvivekm** [comment] 2023-05-06 22:03
There you go @duckling69

**Comment by Pranjal7852** [comment] 2023-05-10 19:55
can i also work on this issue?

**Comment by aminoxix** [comment] 2023-05-14 18:06
hey @duckling69, Is it still persist?

**Comment by duckling69** [comment] 2023-05-14 18:13
> hey @duckling69, Is it still persist?

yes I asked for help in discuss.meshery.io no one responded if you would like to work on this issue you can take it up

**Comment by sudhanshutech** [comment] 2023-05-18 10:29
What's the status here ?
@aminoxix are you want take this up

**Comment by aminoxix** [comment] 2023-05-18 10:31
yeah for sure! ✅

**Comment by Ykumar1415** [comment] 2023-06-21 10:19
i want to work on this issue can you assign this to me ?.

**Comment by aminoxix** [comment] 2023-06-21 10:39
So, our (me & @Abhishek-kumar09) research over here: There appears to be a server-side factor that is causing the search functionality to be deactivated. While it appears to be functioning on one end, it would be beneficial to hear Abhishek's insights as he may have a more articulate explanation for this phenomenon.

**Comment by jivteshsingh** [comment] 2023-07-02 12:58
I would like to work on this issue. Can u assign it to me?

**Comment by Abhishek-kumar09** [comment] 2023-07-02 18:00
@jivteshsingh First of all you have to validate this issue by reproducing it on your side.

Here is how you can do a conformance test: https://docs.meshery.io/guides/smi-conformance

**Comment by jivteshsingh** [comment] 2023-07-02 18:06
@Abhishek-kumar09 Thanks for the clarification. I will check and let you know.

**Closed** 2023-09-07 14:25 UTC
Labels: kind/bug, help wanted, language/javascript, component/ui, priority/high, framework/react, issue/remind
