### ISSUE TITLE
[Docs] Typo "visitior" in sharing-a-design

### ISSUE THREAD

**Issue by captain-Akshay** [meshery/meshery#8925] opened 2023-09-26 06:30 UTC
### Typo

![image](https://github.com/meshery/meshery/assets/59491379/6e435808-86b6-4a51-84d2-163808081900)

### Desired State
[https://docs.meshery.io/extensions/sharing-a-design](url)
It should be 'visitor'

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment] 2023-09-26 06:31
i would like to work for this issue

**Comment by akhilender-bongirwar** [comment] 2023-09-26 06:40
@captain-Akshay , we appreciate your enthusiasm to contribute but kindly consider reviewing existing open issues in Meshery prior to contributing. This issue you have raised is duplicate of #8911

**Comment by captain-Akshay** [comment] 2023-09-26 06:44
yes i actually went through that @akhilender-bongirwar but that's was on page https://docs.meshery.io/extensions/publishing-a-design
and my apologies but it wasn't clear that it was regarding all the typo "visitior"among the docs that's why i created another as its is for another page

**Closed** 2023-09-26 06:49 UTC
Labels: area/docs, language/markdown, framework/jekyll
