### ISSUE TITLE
[UI] Meshery's Color Audit

### ISSUE THREAD

**Issue by Chadha93** [meshery/meshery#8572] opened 2023-08-23 09:33 UTC
### Current Behavior
The colors of text, and icons are not consistent according to the design system. 

### Desired Behavior
Use theme-based references for texts and icons for light and dark modes. 
Follow the design system mentioned in this [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=110-1&mode=design&t=pq59ZRJLnBmVNjtc-0) for icons and text coloring for different states.

_A new repository for design system - [systent](https://github.com/layer5io/sistent)._

Checklist: (To be updated)

- [ ] Settings Page - Navigation Tabs, checkbox, table components...
- [x] Notification Center - Details and tabs.
- [x] Configuration Page - Designs, Applications, Filters.
- [x] Performance and Performance Profiles.
- [x] Dashboard.
- [x] Connections Page.

### Implementation
The issue is divided into checklists. Mention the items or component names in the PR according to the checklist.

### Acceptance Tests
1. Add colors to the root-level theme for the MUI components.
2. No hardcoding of colors, only theme-based reference.

### Mockups

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anmolchhabra21** [comment] 2023-08-23 10:51
Hi @Chadha93, if this issue is still pending, I would like to work upon this issue.

**Comment by Chadha93** [comment] 2023-08-24 14:16
Sure @singh1203.

**Comment by Chadha93** [comment] 2023-08-24 14:18
@anmolchhabra21 Let's divide the checklist between you and @singh1203. 

@singh1203 :
- [ ] Settings Page - Navigation Tabs, checkbox, table components...
- [ ] Notification Center - Details and tabs.
- [ ] Configuration Page - Designs, Applications, Filters.

@anmolchhabra21 : 
- [ ] Performance and Performance Profiles.
- [ ] Dashboard.
- [ ] Connections Page.

**Comment by Chadha93** [comment] 2023-08-24 14:19
Let's set an ETA for this, next Wednesday. 
Sounds good @singh1203 and @anmolchhabra21?

**Comment by singh1203** [comment] 2023-08-24 14:24
> Let's set an ETA for this, next Wednesday. Sounds good @singh1203 and @anmolchhabra21?

Cool. Thank you @Chadha93

**Comment by anmolchhabra21** [comment] 2023-08-24 14:31
> 

Ok. I'll work on that.

**Comment by Ghat0tkach** [comment] 2023-09-07 15:16
@singh1203 @anmolchhabra21 
Any updates?

**Comment by singh1203** [comment] 2023-09-10 14:30
@Ghat0tkach To be very frank, we are not able to find the root component, I think we need guidance to move further. 
Thank you.

**Comment by anmolchhabra21** [comment] 2023-09-10 14:42
@Ghat0tkach, sorry for the late reply, Actually I was not available for the past week due to very urgent commitment, just give me some time, I'll try to finish it asap, if not encountered by any serious error or bug.
And as @singh1203 said, I think there was some hard-coded stuff on the div, So will have to dive deeper.

**Comment by Ghat0tkach** [comment] 2023-09-10 21:53
@anmolchhabra21 and @singh1203 , how bout lets discuss this on monday's weekly website meeting minutes?
here is the link , please add this as an agenda 
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk

**Comment by Yana-Gupta** [comment] 2023-09-28 04:31
@Chadha93 Shall I work on this issue. If the issue is still pending. WIll you assign me.

**Comment by leecalcote** [comment] 2023-09-30 15:07
@Yana-Gupta sound good.

**Comment by sandramsc** [comment] 2024-01-04 11:02
This issue has been open for some time with no recent activity, unassigning to open it up for new contributors to give it a go.

**Comment by singh1203** [comment] 2024-03-30 07:29
@sandramsc I think this issue can be closed as the new Meshery UI has been implemented. Thank you!

**Closed** 2024-09-01 07:44 UTC
Labels: kind/enhancement, help wanted, language/javascript, component/ui, issue/willfix, framework/react
