### ISSUE TITLE
[UI] Page horizontal scroll

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#8286] opened 2023-07-26 19:41 UTC
#### Current Behavior

In configuration Filters and Designs page has horizontal scroll.

#### Desired Behavior

Page should be responsive without any horizontal scroll

#### Screenshots/Logs

https://github.com/meshery/meshery/assets/52546856/a2254902-e8ef-447e-ab94-1e5631ea52d3

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by supzi-del** [comment] 2023-07-26 20:04
Can I take this up?

**Comment by sivasathyaseeelan** [comment] 2023-07-26 20:34
Hi @senali-d, I would like to work on this issue. Can you please assign it to me?

**Comment by Yana-Gupta** [comment] 2023-07-27 07:57
Hi @senali-d I would like to work on this issue. Would you assign me.

**Comment by duckling69** [comment] 2023-07-28 06:42
Assigning to @supzi-del .. // @sivasathyaseeelan @Yana-Gupta you can take up some other issue in meantime ^^

**Comment by anmolchhabra21** [comment] 2023-08-23 11:04
Hi @senali-d, If this is still pending, I would like to work upon this.

**Comment by Manish4044** [comment] 2023-09-11 04:36
If the issue is still there, @senali-d can I get to work on this ?

**Comment by Manish4044** [comment] 2023-10-19 12:04
I am working on it. I need a little more time. Facing issues with setup

**Comment by Manish4044** [comment] 2023-10-27 04:20
This issue no longer exists in the current stable version. It is already fixed as part of another Pull Request in August 2023 release.

PR Link : https://github.com/meshery/meshery/pull/8357

Release Link: https://docs.meshery.io/project/releases/v0.6.115#:~:text=%5BResponsiveness%5D%20%2D%20Made%20Configurations%20design%20page%20responsive%20%40UsmanDev09%20(%238357)

**Comment by Manish4044** [comment] 2023-11-02 15:42
Hey @saurabh100ni @senali-d, any follow up on my previous comment? I think the issue is already fixed by a different PR. So maybe we can close this now

**Comment by saurabh100ni** [comment] 2023-11-02 16:15
I see, Thanks for the update @Manish4044

**Closed by saurabh100ni** 2023-11-02 16:15 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react, issue/remind
