### ISSUE TITLE
[Helm] Meshery Adapter for Cilium being deployed under Meshery Operator chart

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#5654] opened 2022-06-20 16:56 UTC
#### Current Behavior
In Meshery deployments to `docker` as the platform, the Meshery Adapter for Cilium being deployed to the `meshery` namespace along with the Meshery Operator and its custom controllers. The Meshery Adapter for Cilium being deployed under Meshery Operator chart and is failing to start.

#### Desired Behavior
This adapter should not be deployed under the [Meshery Operator chart](https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery-operator), but only under the [Meshery chart](https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery).

#### Logs
```
meshery        meshery-broker-0                         2/2     Running            0               2d18h
meshery        meshery-cilium-c9ff569b7-87hl5           0/1     ImagePullBackOff   0               2d18h
meshery        meshery-meshsync-578c954545-wktgp        1/1     Running            3 (2d18h ago)   2d18h
meshery        meshery-operator-84c77dd96f-r46h2        2/2     Running            0               2d18h
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment] 2022-06-20 18:54
@hershd23 fyi

**Comment by hershd23** [comment] 2022-06-20 19:14
Will look into it

**Comment by leecalcote** [comment] 2022-06-20 19:25
I'm nearly certain this is an issue that I have caused.

**Comment by hershd23** [comment] 2022-06-25 10:46
https://github.com/meshery/meshery/tree/master/install/kubernetes/helm/meshery-operator#readme

The enabled value for this is set to false under meshery-operator.

@leecalcote all service mesh adapters are there in the meshery-operator chart. Do we want to remove the cilium chart from there?

**Comment by leecalcote** [comment] 2022-07-01 11:10
@Revolyssup

**Comment by Revolyssup** [comment] 2022-07-03 06:11
@hershd23 Did you try to repro this? If you run Meshery, it deploys it's custom controllers using the operator helm chart but somehow a cilium deployments also kicks in with the same helm chart. So it is to investigate as to what overrides and where is causing this issue.

**Comment by hershd23** [comment] 2022-07-04 17:08
```
(base)  hersh.dhillon@BLRETV-C02F49CL  ~/personal_projects/projects/meshery/mesheryctl   master ±  kubectl get pods --all-namespaces
NAMESPACE     NAME                                READY   STATUS    RESTARTS        AGE
kube-system   coredns-78fcd69978-zzmx4            1/1     Running   0               10m
kube-system   etcd-minikube                       1/1     Running   0               10m
kube-system   kube-apiserver-minikube             1/1     Running   0               10m
kube-system   kube-controller-manager-minikube    1/1     Running   0               10m
kube-system   kube-proxy-gd5zw                    1/1     Running   0               10m
kube-system   kube-scheduler-minikube             1/1     Running   0               10m
kube-system   storage-provisioner                 1/1     Running   1 (9m36s ago)   10m
meshery       meshery-broker-0                    2/2     Running   0               3m38s
meshery       meshery-dbcf8bbc9-474gc             1/1     Running   0               4m8s
meshery       meshery-meshsync-f6bb4878c-tjtgq    1/1     Running   1 (3m20s ago)   3m38s
meshery       meshery-operator-586c6f895d-5jpkq   2/2     Running   0               4m8s
```

Strange not able to reproduce it

**Comment by leecalcote** [comment] 2022-07-28 19:44
This issue is still occurring.

**Comment by leecalcote** [comment] 2022-09-07 03:39
@acald-creator, perhaps you would like to take this on?

**Comment by acald-creator** [comment] 2022-09-07 04:04
@leecalcote Of course, sure I can.

**Comment by Aisuko** [comment] 2023-02-03 09:47
Is this issue still occurring?

**Comment by acald-creator** [comment] 2023-02-03 18:46
It shouldn't be, last I deployed `mesheryctl`, `cilium` was still running. we can close this issue, and we also fixed through with the revamp of the helm charts a couple months ago or so.

**Closed** 2023-02-03 18:47 UTC
Labels: help wanted, area/ci, issue/willfix, issue/remind, service-mesh/cilium, framework/helm

**Comment by Aisuko** [comment] 2023-02-04 07:28
Thank you.
