### ISSUE TITLE
[Docs] Dark mode logo issue for Meshery Adapter of Kuma

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7995] opened 2023-06-29 13:31 UTC
### Description
logo of   Meshery Adapter for Kuma not visiable in dark mode at  https://docs.meshery.io/

### Expected Behavior
logo should be visiable

### Screenshots
<img width="193" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/e3aecb49-b7de-4dad-92f9-3552616f0b24">

<img width="197" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/0a538de5-4f7c-410b-b5b7-1d046deb4af9">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by bupd** [comment] 2023-07-04 23:13
#7995 This issue is the same as #7981 
@Chadha93 
Do we need to work on this issue twice.

**Comment by Rajivkumawat3** [comment] 2023-07-05 05:28
@bupd this  issue is transfered not assigned

**Comment by thisiskaransgit** [comment] 2023-07-06 13:15
duplicate of #7981

**Closed** 2023-07-06 13:15 UTC
Labels: kind/bug
