### ISSUE TITLE
[UI] Designs page design visibility label typo update

### ISSUE THREAD

**Issue by senali-d** [meshery/meshery#7682] opened 2023-05-13 19:33 UTC
#### Current Behavior

[Designs page](https://playground.meshery.io/configuration/designs): designs that have visibility of “Published” are showing with the label of “Public”

#### Desired Behavior

Change the label “Public” into “Published”

##### Current Behavior
![1](https://github.com/meshery/meshery/assets/52546856/14a7a784-07e9-4a54-b9f7-83386fadc417)

##### Desired Behavior
![2](https://github.com/meshery/meshery/assets/52546856/c3e40257-56b8-4dbe-a1a9-f9c537e153e4)

#### Environment

- Browser: Chrome Safari Firefox
- Host OS: Mac Linux Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by duckling69** [comment] 2023-05-13 19:50
I'd like to work on the issue

**Comment by aminoxix** [comment] 2023-05-14 07:07
yeah sure @duckling69 , here you go! 🚀

**Comment by duckling69** [comment] 2023-05-14 17:45
Hey @aminoxix done with all my issues you can reassign if you want :)

**Comment by ciradu2204** [comment] 2023-05-16 18:37
Hi, can I work on this?

**Comment by aminoxix** [comment] 2023-05-16 18:39
hey @ciradu2204, thanks for your interest, actually, I'm currently working on this issue, you can pick some other deffo! 🙂

**Comment by sudhanshutech** [comment] 2023-05-18 10:49
have you figured out the cause @aminoxix

**Comment by aminoxix** [comment] 2023-05-18 15:35
@senali-d I don't have access to Figma as of now, can you pls drop the `published.svg` here to update the image?

Or better I should assign @duckling69 for this stuff, & I'll take over the fix of the searching issue, which gonna be my next task.

![image](https://github.com/meshery/meshery/assets/75872316/63152dfa-6b91-40d7-9485-ae0a16c48c9b)

@duckling69 would you like to take this up? just need to update [this image](https://github.com/meshery/meshery/blob/master/ui/public/static/img/published.svg) with the new one.

**Comment by duckling69** [comment] 2023-05-18 15:37
> @senali-d I don't have access to Figma as of now, can you pls drop the `published.svg` here to update the image?
> 
> Or better I should assign @duckling69 for this stuff, & I'll take over the fix of the searching issue, which gonna be my next task.
> 
> ![image](https://user-images.githubusercontent.com/75872316/239276700-63152dfa-6b91-40d7-9485-ae0a16c48c9b.png)
> 
> @duckling69 would you like to take this up? just need to update [this image](https://github.com/meshery/meshery/blob/master/ui/public/static/img/published.svg) with the new one.

Sure

**Comment by senali-d** [comment] 2023-05-18 15:47
@aminoxix You can easily develop the "Published" tag easily using css instead of using image. It will also improve the performance (Reduce one request to load a image).
// @duckling69

**Comment by senali-d** [comment] 2023-06-02 16:34
@duckling69 Any progress

**Closed** 2023-07-01 02:36 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react
