### ISSUE TITLE
[Docs] Commands need to be updated.

### ISSUE THREAD

**Issue by aadityadike** [meshery/meshery#9031] opened 2023-10-06 04:26 UTC
### Current State
I was setting up Meshery using Minikube when I realized that the command provided in the Meshery documentation to connect to Minikube is outdated. This is due to the updated container names, so we need to update the commands accordingly.
**old commands**
`docker network connect bridge meshery_meshery_1`

`docker network connect minikube meshery_meshery_1`

### Desired State
**updated commands**
`docker network connect minikube meshery-meshery-1`

`docker network connect bridge meshery-meshery-1`

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by aadityadike** [comment] 2023-10-06 04:27
Hi, I would like to work on this issue, can I have it assigned to me please with hacktoberfest label?

**Comment by Lymah123** [comment] 2023-10-06 09:16
Hi, I would like to work on the issue if no one has been assigned to it yet.

**Closed** 2023-10-08 06:02 UTC
Labels: area/docs, language/markdown, framework/jekyll

**Comment by Exar04** [comment] 2023-10-11 17:38
hey @aadityadike i had reverted my pr as i didn't saw you wanted to make contribution. so ... i guess the issue is still valid

**Comment by aadityadike** [comment] 2023-10-11 23:22
So should I recreate the issue, after varification

**Comment by Exar04** [comment] 2023-10-12 06:28
idk, just make a pr and tag this issue i guess
