### ISSUE TITLE
[Docs] Update docs with `mesheryctl app` command

### ISSUE THREAD

**Issue by suhaniii** [meshery/meshery#3874] opened 2021-08-13 16:24 UTC
#### Current State
 [Docs](https://docs.meshery.io/reference/mesheryctl) doesn't have meshery cli command `mesheryctl app`

#### Desired State

Update [Docs](https://docs.meshery.io/reference/mesheryctl) with  `app` command

### Implementation Guide 
Describe / add command, flag & function in [Docs](https://docs.meshery.io/reference/mesheryctl)  for
`app onboard`
`app offboard`
`app view`
`app list`
All the information can be found in [Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by afzal442** [comment] 2021-08-14 00:32
Duplicate of #3829

**Closed** 2021-08-14 03:05 UTC
Labels: area/docs, framework/jekyll
