### ISSUE TITLE
video height issue in mobile devices

### ISSUE THREAD

**Issue by Rajivkumawat3** [meshery/meshery#7998] opened 2023-06-29 13:40 UTC
### Description
when we visit https://docs.meshery.io/extensions/ there are some issue at mobile devices  in media queries we have to change height of vedio  because after start the video most of the spaces did not in use , so i am showing some pictures current and desired behaviour , first 2 pictures are current behavior in mobile devices and last two are expected behaviour  in mobile devices

### Expected Behavior
expected behaviour are in pictures

### Screenshots

<img width="258" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/c99c165f-9066-4fff-a2c0-bc8aa4548de6">
<img width="259" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/739b4ff6-e097-4a13-82d7-e3ed090a68b5">
<img width="251" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/0739a3da-0534-4a86-a61c-71dd1ae35fcb">
<img width="241" alt="image" src="https://github.com/meshery/meshery.io/assets/122862213/db440cf1-0a0f-4bc1-949f-68e559c28de7">

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by thisiskaransgit** [comment] 2023-06-30 20:32
Duplicate of #7980

**Closed** 2023-06-30 20:32 UTC
Labels: kind/bug
