### ISSUE TITLE
[Docs] Image link broken in "mesheryctl app onboard" docs

### ISSUE THREAD

**Issue by nishantwrp** [meshery/meshery#5977] opened 2022-08-05 18:50 UTC
#### Current State
https://docs.meshery.io/reference/mesheryctl/app/onboard

<img width="1440" alt="Screenshot 2022-08-06 at 12 18 30 AM" src="https://user-images.githubusercontent.com/36989112/183142198-e2cbac86-e7cc-464a-b585-fde195a0769c.png">

#### Desired State

Have [this](https://github.com/meshery/meshery/blob/master/docs/assets/img/mesheryctl/app-onboard.png) image displayed correctly instead of the broken image.

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment] 2022-08-05 20:32
@mihir2226 over here.

**Comment by mihir2226** [comment] 2022-08-05 20:36
@leecalcote yeap assign me this issue.

**Comment by leecalcote** [comment] 2022-08-05 20:37
Question, @mihir2226: Have you built/run a Jekyll site before? If not, please confirm that you're successful making and running Meshery Docs and then let's get you assigned. 👍

**Comment by mihir2226** [comment] 2022-08-05 20:38
ok it's the first time I will try to build and run it first as you say

**Comment by leecalcote** [comment] 2022-08-05 23:33
It looks like this is fixed by #5908.

**Comment by mihir2226** [comment] 2022-08-06 00:21
@leecalcote ok, I spent all night but I'm not able to set up everything. do you guide me?

**Comment by leecalcote** [comment] 2022-08-06 00:22
See the recorded presentations on meshery.io/community/newcomers. Bottom the page. 

Note, that someone else already fixed this particular issue.

**Comment by abhiyant-10** [comment] 2022-08-07 08:20
The image is still not visible to me , if the issue is still there I would like to work on it . I have jekyll set as I have worked on meshery docs before

**Closed** 2022-08-13 08:15 UTC
Labels: help wanted, good first issue, area/docs, language/markdown, framework/jekyll
