### ISSUE TITLE
[mesheryctl] Myopic logic in `system status` and `system stop`

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#3795] opened 2021-08-05 21:00 UTC
_See [mesheryctl Command Tracker](https://bit.ly/3dqXy1q) for current status of commands._

#### Current Behavior
```
➜  Meshery mesheryctl system stop
Meshery is not running. Nothing to stop.
➜  Meshery mesheryctl system status
Meshery is not running. Run `mesheryctl system start` to start Meshery.
➜  Meshery kubectl get pods -n meshery
NAME                                    READY   STATUS    RESTARTS   AGE
meshery-broker-0                        2/2     Running   0          2m7s
meshery-consul-dcdb77f96-wvjtp          1/1     Running   0          3m47s
meshery-cpx-79fb9656bc-4rcbd            1/1     Running   0          3m47s
meshery-istio-64c757bbc8-hhcp6          1/1     Running   0          3m47s
meshery-kuma-6669cc5979-g92wh           1/1     Running   0          3m47s
meshery-linkerd-5c8c7756db-2hhss        1/1     Running   0          3m47s
meshery-meshsync-7cc779c8bb-rtmpd       1/1     Running   5          3m27s
meshery-nsm-78b44df4f6-lljgs            1/1     Running   0          3m47s
meshery-operator-bddf9fd66-ndqbn        2/2     Running   0          3m47s
meshery-osm-7bb65bf558-z9txc            1/1     Running   0          3m46s
meshery-traefik-mesh-6778958fd4-qt865   1/1     Running   0          3m46s
```

#### Desired Behavior
These two commands should not only take `meshery` into consideration but all components listed in the `current-context`.

- Host OS: Mac
- Meshery Server Version: stable-v0.5.42
- Meshery Client Version: stable-v0.5.42
- Platform: Kubernetes

---

#### Contributor Resources
- [mesheryctl Contributing Guide](https://github.com/meshery/meshery/blob/master/mesheryctl/README.md)
- [Beginner's guide to contributing to Meshery and mesheryctl](https://youtu.be/hh_kFLZx3G4)
- [mesheryctl Command Tracker](https://docs.google.com/spreadsheets/d/1q63sIGAuCnIeDs8PeM-0BAkNj8BBgPUXhLbe1Y-318o/edit#gid=0)
- [Meshery CLI Commands and Documentation](https://docs.google.com/document/d/1xRlFpElRmybJ3WacgPKXgCSiQ2poJl3iCCV1dAalf0k/edit#heading=h.5fucij4hc5wt)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by metonymic-smokey** [comment] 2021-08-09 09:50
@leecalcote So this is what I think about changing this logic:

This is the existing code(`IsMesheryRunning`) which checks if meshery is running: 
https://github.com/meshery/meshery/blob/4a5ebbe84032e337f97f8386339671dfdc15e89c/mesheryctl/pkg/utils/healthcheck.go#L128-L135
This function is called in `status.go`

After this in the same function, in the Kubernetes section, there is already [code](https://github.com/meshery/meshery/blob/4a5ebbe84032e337f97f8386339671dfdc15e89c/mesheryctl/pkg/utils/healthcheck.go#L169-L171) that checks the status of each pod and returns true if any meshery pods are  running.    

So in my opinion, the part checking status based on the HTTP response from the API should be moved to after checks based on platform, instead of before.

**Comment by metonymic-smokey** [comment] 2021-08-09 09:51
Once `IsMesheryRunning` is fixed, this issue in `system stop` should be fixed too, since it is used as a preliminary check there too. 

Let me know what you think!

**Comment by metonymic-smokey** [comment] 2021-08-11 05:20
@leecalcote could you please tell me the steps to reproduce this issue?
I never seem to face it locally.
Thanks!

**Comment by navendu-pottekkat** [comment] 2021-08-13 12:37
@leecalcote This might be the case when you have deployed Meshery on Kubernetes but the platform in the meshconfig is `docker`.

In both the cases, it would be best if we check the `meshery` namespace as well and stop anything that is running there.

// @metonymic-smokey

**Comment by metonymic-smokey** [comment] 2021-08-16 03:11
@navendu-pottekkat so perform the check of the namespace for both platforms?

**Comment by navendu-pottekkat** [comment] 2021-08-16 06:32
Yes and check for any existing pods as well. Even if the Meshery pod is deleted, check for the other pods.

**Comment by leecalcote** [comment] 2021-08-16 07:26
Right - both stop and status need fixed.

**Comment by alphaX86** [comment] 2021-11-07 13:09
Sorry for looking this late, but are we considering k8s here or docker?

**Comment by alphaX86** [comment] 2021-11-07 13:14
For k8s, I manually stopped Meshery pod and left others to run, all were working fine. For Docker, I didn't test yet

**Comment by navendu-pottekkat** [comment] 2021-11-25 11:22
@alphaX86 Are you tracking this issue?

When we consider multi-cluster support, having just the operator deployed on a cluster is a valid use-case. The current logic in mesheryctl as mentioned above is that it only checks for Meshery server pods to decide if Meshery is running.

The ask here is to change that logic to check the namespace and the status of the pods to determine Meshery is running and provide a better UX to the user so that he can choose to delete orphaned operator deployments if needed.

Let me know if you will be able to take this up.

**Comment by leecalcote** [comment] 2022-01-01 21:22
Progress to report?

**Comment by leecalcote** [comment] 2022-01-31 14:40
Perhaps, a `--force` flag could be added here with the behavior to execute the `stop()` logic irrespective of Meshery Server status.

**Comment by piyushsingariya** [comment] 2022-01-31 15:09
> @leecalcote This might be the case when you have deployed Meshery on Kubernetes but the platform in the meshconfig is `docker`.

@leecalcote I think this was the case with your system back then, because it is not reproducible in my local system.
Meshery Server status is just a case added to maintain few mesheryctl commands which checks if meshery is running and if someone is running via local build.

**Closed** 2022-02-03 14:54 UTC
Labels: kind/bug, component/mesheryctl, language/go, issue/willfix
