### ISSUE TITLE
[UI] Theme Toggler Button Fix

### ISSUE THREAD

**Issue by Abbhiishek** [meshery/meshery#8931] opened 2023-09-26 13:31 UTC
### Current Behavior

Currently dark/ light theme toggler is not center aligned with other navbar elements. Also the elements has hover effect which include both underline and background color change.

<img width="911" alt="image" src="https://github.com/meshery/meshery/assets/86338762/a3a89166-89f7-4d09-b8f7-d5f4ca123d5c">

### Desired Behavior

The theme toggler can be centered aligned to make it uniform through out the navbar. I would love to work on this issue.

### Screenshots/Logs

<img width="1082" alt="image" src="https://github.com/meshery/meshery/assets/86338762/edb74c69-3196-4078-9101-c5d53a1579d0">

### Environment

- Browser: Chrome
- Host OS: Windows
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform: Docker Kubernetes

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by captain-Akshay** [comment] 2023-09-26 13:37
I would like to work on this please assign it to me !

**Comment by EraKin575** [comment] 2023-09-26 14:33
the issue is on this repo: https://github.com/meshery/meshery.io

**Comment by Abbhiishek** [comment] 2023-09-26 14:38
I came across this issue : https://github.com/meshery/meshery.io/issues/1386

its already registered ...

**Comment by Lakhaninawaz** [comment] 2023-09-26 17:24
anyone help me in i locally work in ui. after click on get token 500 error show. how to solve this?

**Comment by Narottamchy** [comment] 2023-09-26 18:57
please assign this issue to me

**Comment by Mohith234** [comment] 2023-09-28 07:16
Closing this issue as it is already reported

**Closed by Mohith234** 2023-09-28 07:16 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react
