### ISSUE TITLE
[Enhancement][UI] Labels size is bigger than the value in Node details page

### ISSUE THREAD

**Issue by ritiksaxena124** [meshery/meshery#9865] opened 2024-01-08 11:12 UTC
### Current Behavior
On a smaller screen, the label of the field is very much larger than the value which makes it hard to read and get the actual value provided.
![image](https://github.com/meshery/meshery/assets/51539117/abc33008-ceff-442c-b832-0fad63ea5a37)

### Desired Behavior
Reduce the font size of the labels 

**How to reproduce the issue?**
1. Open the dashboard of Meshery UI in the browser and inspect the page
2. Select the Dimensions of any mobile size
3. Click on the Node tab 
4. Click on any of the rows - this will take you to the node details page

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by Somnath-sanu** [comment] 2024-01-08 13:46
**Couldn't reproduce the issue.** 
Kindly provide the detail step ->###  How to navigate to dashboard in browser??

**Comment by Raj100679** [comment] 2024-01-08 17:51
@ritiksaxena124 Can you assign this to me

**Comment by shourya2002-geek** [comment] 2024-01-10 13:36
Hi @ritiksaxena124 , is it possible if I could work on this issue, if it has not been assigned yet ?

**Comment by Raj100679** [comment] 2024-01-11 18:16
@ritiksaxena124 Can you assign me this?

**Comment by ameeetgaikwad** [comment] 2024-01-12 17:13
would like to work on this!

**Comment by ritiksaxena124** [comment] 2024-01-12 18:22
Thanks for your interest in the issue folks, as we assign contributors on a first come first serve basis. So @Somnath-sanu do you want to tackle this or should we pass it to @shourya2002-geek?

**Comment by Somnath-sanu** [comment] 2024-01-13 05:43
I apologize for the delay in completing the task . Unfortunately, due to certain reasons, I won't be able to do it.. @ritiksaxena124  please pass it to @shourya2002-geek

**Comment by sudhanshutech** [comment] 2024-01-18 18:36
@cesartheroman

**Comment by cesartheroman** [comment] 2024-01-18 18:50
@sudhanshutech Absolutely!

**Comment by cesartheroman** [comment] 2024-01-23 19:57
@sudhanshutech Just wanted to give a brief update on my progress, since I started working on this issue today (Jan 23rd):

- Was able to fork and clone down repo
- Was able to get Meshery UI running locally
- Was able to get Meshery Server running locally via Docker Meshery extension.

What I will focus on now is trying to replicate the issue. I'm a bit stuck since I'm not sure how to add more nodes in the local version of Meshery and without any test nodes, I won't be able to replicate the issue. I've looked through the docs but maybe I'm not looking in the right places? Regardless, I'll show up to the Meshery Dev Meeting tomorrow to see if I can get any help.

**Closed** 2024-02-06 19:08 UTC
Labels: kind/enhancement
