### ISSUE TITLE
[UI] While uploading the config file again it' s get  uploaded

### ISSUE THREAD

**Issue by Akshit42-hue** [meshery/meshery#5519] opened 2022-05-17 03:56 UTC
#### Current Behavior

Even the config file has been uploaded and trying to upload the same file again it's get uploaded and as a result the number of cluster get increase.  

#### Desired Behavior

If trying to upload the same config file again it should not be uploaded again

#### Screenshots/Logs

![Screenshot from 2022-05-17 13-22-37](https://user-images.githubusercontent.com/59443454/168760461-c848436e-61e8-4d5f-b4b6-2dcc32823a89.png)

#### Environment

- Browser: Chrome 
- Host OS:  Linux 
- Meshery Server Version: stable-v
- Meshery Client Version: stable-v
- Platform:  Kubernetes

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources

- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by warunicorn19** [comment] 2022-05-17 14:30
@Revolyssup @theBeginner86 are you guys able to recreate this?

**Comment by kayceeDev** [comment] 2022-06-23 10:35
I will take a look at this issue. Do I need to have both meshery server and the UI server running simultaneously?

**Comment by MUzairS15** [comment] 2022-06-23 11:11
> I will take a look at this issue. Do I need to have both meshery server and the UI server running simultaneously?

Yes @kayceeDev

**Comment by Chadha93** [comment] 2022-07-15 09:48
@warunicorn19 @theBeginner86 Is this still an issue? Let's close this one if not.

**Comment by warunicorn19** [comment] 2022-07-15 13:12
i  wasn't able to recreate this before either. Need confirmation from others.

**Comment by theBeginner86** [comment] 2022-07-15 14:44
I too can't reproduce this behaviour.

**Comment by Chadha93** [comment] 2022-07-15 17:14
Thank you for confirming @warunicorn19 @theBeginner86.

**Closed by Chadha93** 2022-07-15 17:14 UTC
Labels: kind/bug, language/javascript, component/ui, framework/react
