### ISSUE TITLE
[UI] Text being cutoff in Namespace dropdown

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#2598] opened 2021-03-25 15:27 UTC
#### Description
The bottom of the text in this dropdown is being cutoff. This dropdown is on the http://localhost:9081/management?adapter=meshery-linkerd:10001 page

#### Screenshots/Logs
<img width="1058" alt="Screen Shot 2021-03-25 at 10 26 02 AM" src="https://user-images.githubusercontent.com/7570704/112498597-ae8a4a80-8d54-11eb-898c-c3eef14677ed.png">

#### Environment:
- Meshery Version: v0.5.0
- Browser: Safari

**Comment by onwuvic** [comment] 2021-03-26 10:47
@leecalcote can I take this up?

**Comment by leecalcote** [comment] 2021-03-26 13:56
@onwuvic, very good. Yes, thank you for volunteering. 🙂

**Comment by onwuvic** [comment] 2021-04-05 06:36
@adithyaakrishna I got caught up with work. Please you can take it up

**Comment by adithyaakrishna** [comment] 2021-04-05 10:43
Thank You @onwuvic :)

**Comment by adithyaakrishna** [comment] 2021-04-05 18:21
Hey @leecalcote, Can you please assign me this? :)

**Comment by leecalcote** [comment] 2021-04-05 18:30
Sounds good. Thank you, @onwuvic, @adithyaakrishna

**Comment by adithyaakrishna** [comment] 2021-04-10 12:58
Hey @leecalcote 
I guess this issue is fixed way long ago, not sure which PR but I was about to work on this, but saw it was coming properly,
Here's the SS of the same :)
![image](https://user-images.githubusercontent.com/23498248/114270528-8116ef80-9a2a-11eb-902d-bb5aca848b34.png)

**Comment by adithyaakrishna** [comment] 2021-04-11 15:29
I checked the same across 3 browsers, Firefox, Chrome and Edge but the text was not being cut off. @leecalcote Please do let me know if this is a browser specific issue 👀

**Comment by adithyaakrishna** [comment] 2021-05-22 11:41
Damn you bot, this is not a stale issue. Bad Bot 🤦‍♂️

**Comment by adithyaakrishna** [comment] 2021-07-01 13:18
@Ayush-Khandelwal-007 Do you mind knocking this out, since you have a MacOS based system? 👀

**Comment by Ayush-Khandelwal-007** [comment] 2021-07-01 14:01
😶 I have been using it far quite a time but never came across, I'll check and give update soon.

**Comment by Ayush-Khandelwal-007** [comment] 2021-07-03 16:26
@leecalcote @adithyaakrishna Few days back I made few changes in this screen. Might be possible that it may have fixed this issue as I tried different things but was not able to recreate this bug. Lee can you please check it once more if it still exists.

**Comment by Ayush-Khandelwal-007** [comment] 2021-07-11 09:41
@leecalcote @adithyaakrishna Few days back I made few changes in this screen. Might be possible that it may have fixed this issue as I tried different things but was not able to recreate this bug. Lee can you please check it once more if it still exists.

**Comment by sudo-NithishKarthik** [comment] 2021-07-20 04:24
@leecalcote , i don't think this issue still persist, should we close it ?

**Comment by sudo-NithishKarthik** [comment] 2021-07-27 05:49
I am not able to reproduce this issue, i have tried it in **Safari**, **Brave** and **Chrome**. i think we should close this issue to avoid unnecessary distraction.

**Comment by sudo-NithishKarthik** [comment] 2021-08-11 12:45
Reopening as this issue still persists

**Comment by veerreshr** [comment] 2021-08-16 16:25
I feel this is related to some styling, could I work on this?

**Comment by sudo-NithishKarthik** [comment] 2021-08-17 05:53
Sure @veerreshr , go ahead 🚀

**Comment by veerreshr** [comment] 2021-08-20 13:53
Hey I can't replicate this issue in my machine , I tried with firefox and brave. Could someone confirm if this happens with safari?

**Comment by sudo-NithishKarthik** [comment] 2021-08-21 07:07
Yes @veerreshr , it happens only with safari.

**Comment by leecalcote** [comment] 2021-08-24 22:45
Thanks for looking into this, @veerreshr. Do you have access to Safari? If not, let's get you connected with someone who does and have you either collaborate with them or transfer the issue. // @warunicorn19

**Comment by veerreshr** [comment] 2021-08-24 23:11
I don't have access to it @leecalcote , may be assign it to some other person.

**Comment by asubedy** [comment] 2021-10-02 04:21
I would like to work in this, please assign me.

**Comment by gauravmishra0** [comment] 2021-12-29 11:01
I want to work on it

**Comment by samirparhi-dev** [comment] 2021-12-29 11:03
thank you for jumping in , yes please !

**Comment by Chadha93** [comment] 2022-01-17 08:25
This seems a Safari Browser-specific issue, Taker's please ensure you have Mac OS for this issue. :)

**Closed** 2022-01-17 15:47 UTC
Labels: kind/bug, help wanted, good first issue, component/ui, framework/react
