### ISSUE TITLE
[Docs] Publish Windows contributor docs for Meshery Server and Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery#7151] opened 2023-02-22 13:42 UTC
#### Current State
Meshery Contributors that use Windows as their operating system are in need of build instructions for Meshery Server and Meshery UI. Instructions have already been written in two Google Docs. These two Google Docs can be combined and published.

Already published: [Meshery Docs with Windows](https://docs.meshery.io/project/contributing/contributing-docs#for-windows) 

#### Desired State
1. Review “[Jekyll Tutorial](https://docs.google.com/document/d/1JoPujIO_dyX3pTHvbGtQ5OBXERlSInac3ecLSkgFFSo/edit#heading=h.ipjd8jcauwx)”. document and publish any missing details into [Meshery Docs with Windows](https://docs.meshery.io/project/contributing/contributing-docs#for-windows) .

2. Combine and publish the contents of these two docs:
    1. “[Setting up your Meshery Development Environment on Windows](https://docs.google.com/document/d/1QHBb3TRhlYDTvcwodnY-KX2v73RYNclL8UPlGE5U2Y8/edit#)”
    2. “[Setting up the Meshery runtime on the local Windows Environment](https://docs.google.com/document/d/1nyFu2oD9s6SDrdo5IwDAhOzbA5-5aSzf7Xh4RZQYol0/edit)”

---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mohit-marathe** [comment] 2023-02-22 14:04
Hello @leecalcote , I would like to work on this issue. Can you please assign it to me?

**Comment by leecalcote** [comment] 2023-02-22 14:38
Thanks for you raising your hand, @mohit-marathe. Yes. I thought you did a swell job on your last docs update as well.

**Comment by Nithin1728** [comment] 2023-02-26 17:21
Hi is this issue still open? I'd like to work on it

**Comment by mohit-marathe** [comment] 2023-02-26 17:54
@Nithin1728 , the issue is open but I'm already working on it.

**Closed** 2023-03-02 04:38 UTC
Labels: help wanted, area/docs, language/markdown, framework/jekyll
